### ISSUE TITLE
Class/id naming conventions 

### ISSUE THREAD

**Issue by aubreywullschleger** [jlegar/tea_cozy#3]
Great!  I like how you've named your `class`/`id` attributes as they describe the content well and help make your HTML easy to understand and read.  Here's an overview of good practices for `class`/`id` naming conventions to use in future projects (plus different naming conventions to try): http://bdavidxyz.com/blog/how-to-name-css-classes/.

Example: https://github.com/jlegar/tea_cozy/blob/master/index.html#L29

**Comment by jlegar** [comment]
Thanks for helpful article.
